<?php

/**
 *
 * Custom Inputfield Dependencies
 *
 * @author Robin Sallis
 * @credits Thanks to Adrian Jones for ideas and helpful feedback
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class CustomInputfieldDependencies extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Custom Inputfield Dependencies',
			'version' => 2,
			'summary' => 'Extends inputfield dependencies so that inputfield visibility or required status may be determined at runtime by selector or custom PHP code.',
			'autoload' => "template=admin",
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		// hooks
		$this->addHookAfter('Field::getConfigInputfields', $this, 'addFieldOptions');
		$this->addHookAfter('Field::getInputfield', $this, 'evaluateCustomDependencies');
	}

	/**
	 * Evaluate any custom inputfield dependencies
	 */
	public function evaluateCustomDependencies($event) {
		if($this->page->process !== 'ProcessPageEdit') return;

		// variables
		$field = $event->object;
		$inputfield = $event->return;
		$page = $event->arguments('page');
		$pages = $this->pages; // mainly to make this variable available as $pages in custom PHP

		// evaluate show-if conditions
		if($field->show_if_custom_find) {
			$matches = $pages->find($field->show_if_custom_find);
			if(!$matches->has($page)) {
				$inputfield->collapsed = Inputfield::collapsedHidden;
			}
		}
		if($field->show_if_selector) {
			$matches = $pages->find($field->show_if_selector);
			if(!$matches->has($page)) {
				$inputfield->collapsed = Inputfield::collapsedHidden;
			}
		}
		if($field->show_if_custom_php) {
			$result = eval($field->show_if_custom_php);
			if($result !== true) {
				$inputfield->collapsed = Inputfield::collapsedHidden;
			}
		}
		// evaluate required-if conditions
		if($field->required && $field->required_if_custom_find) {
			$matches = $pages->find($field->required_if_custom_find);
			if(!$matches->has($page)) {
				$inputfield->required = 0;
			}
		}
		if($field->required && $field->required_if_selector) {
			$matches = $pages->find($field->required_if_selector);
			if(!$matches->has($page)) {
				$inputfield->required = 0;
			}
		}
		if($field->required && $field->required_if_custom_php) {
			$result = eval($field->required_if_custom_php);
			if($result === true) {
				$inputfield->required = 1;
			} else {
				$inputfield->required = 0;
			}
		}
	}

	/**
	 * Helper function for fields in a repeater
	 */
	public function getEditedPage($page) {
		if($page instanceof RepeaterPage) {
			return $this->getEditedPage($page->getForPage());
		} else {
			return $page;
		}
	}

	/**
	 * Add field options
	 */
	public function addFieldOptions($event) {
		// the field being edited
		$field = $event->object;

		// the inputfield wrapper
		$wrapper = $event->return;

		// change to template context of field if fieldgroup ID present in input
		$fieldgroup_id = (int) $this->input->post->fieldgroup_id ?: (int) $this->input->get->fieldgroup_id;
		$fieldgroup = $this->fieldgroups->get($fieldgroup_id);
		if($fieldgroup) $field = $fieldgroup->getFieldContext($field->name);

		// add extra show-if fields
		$f_show_if = $wrapper->getChildByName('showIf');
		$f = $this->makeCustomPhpField('show_if_custom_php');
		$f->value = $field->show_if_custom_php;
		$wrapper->insertAfter($f, $f_show_if);

		$f = $this->makeSelectorField('show_if_selector');
		$f->value = $field->show_if_selector;
		$wrapper->insertAfter($f, $f_show_if);

		$f = $this->makeCustomFindField('show_if_custom_find');
		$f->value = $field->show_if_custom_find;
		$wrapper->insertAfter($f, $f_show_if);

		$fs_visibility = $wrapper->getChildByName('visibility');
		if($field->show_if_custom_find || $field->show_if_selector || $field->show_if_custom_php) {
			$fs_visibility->collapsed = Inputfield::collapsedNo;
		}

		// add extra required-if fields
		$f_required_if = $wrapper->getChildByName('requiredIf');
		$f = $this->makeCustomPhpField('required_if_custom_php');
		$f->value = $field->required_if_custom_php;
		$wrapper->insertAfter($f, $f_required_if);

		$f = $this->makeSelectorField('required_if_selector');
		$f->value = $field->required_if_selector;
		$wrapper->insertAfter($f, $f_required_if);

		$f = $this->makeCustomFindField('required_if_custom_find');
		$f->value = $field->required_if_custom_find;
		$wrapper->insertAfter($f, $f_required_if);

	}

	/**
	 * Make custom find field
	 */
	public function makeCustomFindField($field_name) {
		if($field_name === 'show_if_custom_find') {
			$label = $this->_('Show only if page is matched by custom find');
			$description = $this->_('Add one or more fields below to create a $pages->find() query. If the edited page is matched by the selector then the field is shown. If you prefer to enter this manually, use the "Show only if page is matched by selector" option below instead.');
			$icon = 'question-circle';
		} elseif($field_name === 'required_if_custom_find') {
			$label = $this->_('Required only if page is matched by custom find');
			$description = $this->_('Add one or more fields below to create a $pages->find() query. If the edited page is matched by the selector then the field is required. If you prefer to enter this manually, use the "Required only if page is matched by selector" option below instead.');
			$icon = 'asterisk';
		}
		$f = $this->modules->get('InputfieldSelector');
		$f->name = $field_name;
		$f->label = $label;
		$f->description = $description;
		$f->icon = $icon;
		if($field_name === 'required_if_custom_find') $f->showIf = "required>0";
		$f->collapsed = Inputfield::collapsedBlank;
		return $f;
	}

	/**
	 * Make selector field
	 */
	public function makeSelectorField($field_name) {
		if($field_name === 'show_if_selector') {
			$label = $this->_('Show only if page is matched by selector');
			$description = $this->_('This selector will be passed to a $pages->find("your selector"); statement. If the edited page is matched by the selector then the field is shown.');
			$icon = 'question-circle';
		} elseif($field_name === 'required_if_selector') {
			$label = $this->_('Required only if page is matched by selector');
			$description = $this->_('This selector will be passed to a $pages->find("your selector"); statement. If the edited page is matched by the selector then the field is required.');
			$icon = 'asterisk';
		}
		$f = $this->modules->get('InputfieldText');
		$f->name = $field_name;
		$f->label = $label;
		$f->description = $description;
		$f->icon = $icon;
		if($field_name === 'required_if_selector') $f->showIf = "required>0";
		$f->collapsed = Inputfield::collapsedBlank;
		return $f;
	}

	/**
	 * Make custom PHP field
	 */
	public function makeCustomPhpField($field_name) {
		if($field_name === 'show_if_custom_php') {
			$label = $this->_('Show only if custom PHP returns true');
			$description = $this->_('This statement has access to the $page and $pages API variables, where $page refers to the page being edited. If the snippet returns boolean true then the field is shown.');
			$icon = 'question-circle';
		} elseif($field_name === 'required_if_custom_php') {
			$label = $this->_('Required only if custom PHP returns true');
			$description = $this->_('This statement has access to the $page and $pages API variables, where $page refers to the page being edited. If the snippet returns boolean true then the field is required.');
			$icon = 'asterisk';
		}
		if($this->modules->isInstalled('InputfieldAceExtended')) {
			$f = $this->modules->get('InputfieldAceExtended');
			$f->mode = 'php';
			$f->modes = array('php');
			$f->theme = 'monokai';
		} else {
			$f = $this->modules->get('InputfieldTextarea');
		}
		$f->name = $field_name;
		$f->label = $label;
		$f->description = $description;
		$f->rows = 5;
		$f->icon = $icon;
		if($field_name === 'required_if_custom_php') $f->showIf = "required>0";
		$f->collapsed = Inputfield::collapsedBlank;
		return $f;
	}

}
